# HA Service
apiVersion: v1
kind: Service
metadata:
  name: ha-service
  labels:
    app: ha
spec:
  type: LoadBalancer
  selector:
    app: ha
  ports:
  - port: 8123
    targetPort: 8123

---
# HA Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ha
  labels:
    app: ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha
  serviceName: ha
  template:
    metadata:
      labels:
        app: ha
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - ha
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: ha
        image: homeassistant/home-assistant:latest
        ports:
        - name: ha-port
          containerPort: 8123
          protocol: TCP
        env:
        - name: TZ
          value: America/Chicago
        - name: MYSQL_USER
          value: bello
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: homeassistant
        - name: MYSQL_HOST
          value: mariadb.corobioge9yr.us-east-1.rds.amazonaws.com
        volumeMounts:
        - name: ha-config
          mountPath: /efs-mount-point/run_home_assistant/config
      volumes:
      - name: ha-config
        persistentVolumeClaim:
          claimName: efs-claim

